export interface PhysicsSymbol {
  char: string
  name: string
  latex?: string
  htmlEntity?: string
  unicode?: string
  beschreibung: string
  related?: string[]
  beispiel?: string
}

export interface SymbolCategory {
  id: string
  title: string
  description: string
  symbols: PhysicsSymbol[]
}

export const categories: SymbolCategory[] = [
  {
    id: "griechisch-klein",
    title: "Griechische Kleinbuchstaben",
    description: "Kleinbuchstaben des griechischen Alphabets, die in der Physik als Variablen und Konstanten verwendet werden.",
    symbols: [
      { char: "α", name: "Alpha", latex: "\\alpha", htmlEntity: "&alpha;", unicode: "U+03B1", beschreibung: "Wird oft als Winkel, Winkelbeschleunigung oder Feinstrukturkonstante verwendet.", related: ["Α"], beispiel: "α = ∆ω/∆t (Winkelbeschleunigung)" },
      { char: "β", name: "Beta", latex: "\\beta", htmlEntity: "&beta;", unicode: "U+03B2", beschreibung: "Bezeichnet das Verhaeltnis v/c in der Relativitaetstheorie oder einen Winkel.", related: ["Β"] },
      { char: "γ", name: "Gamma", latex: "\\gamma", htmlEntity: "&gamma;", unicode: "U+03B3", beschreibung: "Lorentzfaktor in der speziellen Relativitaetstheorie, auch Gammastrahlung.", related: ["Γ"] },
      { char: "δ", name: "Delta (klein)", latex: "\\delta", htmlEntity: "&delta;", unicode: "U+03B4", beschreibung: "Kleine Aenderung einer Groesse, Dirac-Deltafunktion oder Kronecker-Delta.", related: ["Δ"] },
      { char: "ε", name: "Epsilon", latex: "\\varepsilon", htmlEntity: "&epsilon;", unicode: "U+03B5", beschreibung: "Elektrische Feldkonstante (Permittivitaet) oder kleine Groesse in der Stoerungstheorie." },
      { char: "ζ", name: "Zeta", latex: "\\zeta", htmlEntity: "&zeta;", unicode: "U+03B6", beschreibung: "Daempfungsverhaeltnis oder Riemann-Zeta-Funktion in der mathematischen Physik." },
      { char: "η", name: "Eta", latex: "\\eta", htmlEntity: "&eta;", unicode: "U+03B7", beschreibung: "Wirkungsgrad, dynamische Viskositaet oder Metrik in der Relativitaetstheorie." },
      { char: "θ", name: "Theta", latex: "\\theta", htmlEntity: "&theta;", unicode: "U+03B8", beschreibung: "Winkel in Polarkoordinaten, Streuwinkel oder Heaviside-Funktion.", related: ["Θ"] },
      { char: "ι", name: "Iota", latex: "\\iota", htmlEntity: "&iota;", unicode: "U+03B9", beschreibung: "Selten in der Physik, gelegentlich als Index oder Laufvariable." },
      { char: "κ", name: "Kappa", latex: "\\kappa", htmlEntity: "&kappa;", unicode: "U+03BA", beschreibung: "Kruemmung, thermische Leitfaehigkeit oder Dielektrizitaetskonstante." },
      { char: "λ", name: "Lambda (klein)", latex: "\\lambda", htmlEntity: "&lambda;", unicode: "U+03BB", beschreibung: "Wellenlaenge, Zerfallskonstante oder Eigenwert in der Quantenmechanik.", related: ["Λ"], beispiel: "λ = c/f (Wellenlaenge)" },
      { char: "μ", name: "My", latex: "\\mu", htmlEntity: "&mu;", unicode: "U+03BC", beschreibung: "Magnetische Permeabilitaet, Reibungskoeffizient, Mikro-Praefix (10^-6) oder reduzierte Masse." },
      { char: "ν", name: "Ny", latex: "\\nu", htmlEntity: "&nu;", unicode: "U+03BD", beschreibung: "Frequenz einer Welle, kinematische Viskositaet oder Neutrino-Symbol." },
      { char: "ξ", name: "Xi", latex: "\\xi", htmlEntity: "&xi;", unicode: "U+03BE", beschreibung: "Dimensionslose Koordinate oder Kohaerenzlaenge in der Supraleitung.", related: ["Ξ"] },
      { char: "π", name: "Pi", latex: "\\pi", htmlEntity: "&pi;", unicode: "U+03C0", beschreibung: "Kreiszahl (3,14159...), fundamentale Konstante in Geometrie und Physik.", related: ["Π"] },
      { char: "ρ", name: "Rho", latex: "\\rho", htmlEntity: "&rho;", unicode: "U+03C1", beschreibung: "Dichte, elektrischer Widerstand (spezifisch) oder Ladungsdichte." },
      { char: "σ", name: "Sigma (klein)", latex: "\\sigma", htmlEntity: "&sigma;", unicode: "U+03C3", beschreibung: "Stefan-Boltzmann-Konstante, Wirkungsquerschnitt, Spannung oder Standardabweichung.", related: ["Σ"] },
      { char: "τ", name: "Tau", latex: "\\tau", htmlEntity: "&tau;", unicode: "U+03C4", beschreibung: "Drehmoment, Zeitkonstante, Lebensdauer oder Schubspannung." },
      { char: "υ", name: "Ypsilon", latex: "\\upsilon", htmlEntity: "&upsilon;", unicode: "U+03C5", beschreibung: "Selten in der Physik; Ypsilon-Meson in der Teilchenphysik." },
      { char: "φ", name: "Phi (klein)", latex: "\\varphi", htmlEntity: "&phi;", unicode: "U+03C6", beschreibung: "Elektrisches Potential, Phasenwinkel oder Azimutwinkel in Kugelkoordinaten.", related: ["Φ"] },
      { char: "χ", name: "Chi", latex: "\\chi", htmlEntity: "&chi;", unicode: "U+03C7", beschreibung: "Magnetische Suszeptibilitaet, Chi-Quadrat-Test oder Wellenfunktion." },
      { char: "ψ", name: "Psi (klein)", latex: "\\psi", htmlEntity: "&psi;", unicode: "U+03C8", beschreibung: "Wellenfunktion in der Quantenmechanik oder Stromfunktion.", related: ["Ψ"] },
      { char: "ω", name: "Omega (klein)", latex: "\\omega", htmlEntity: "&omega;", unicode: "U+03C9", beschreibung: "Kreisfrequenz (2*pi*f), Winkelgeschwindigkeit oder Raumwinkel.", related: ["Ω"], beispiel: "ω = 2πf (Kreisfrequenz)" },
    ],
  },
  {
    id: "griechisch-gross",
    title: "Griechische Grossbuchstaben",
    description: "Grossbuchstaben des griechischen Alphabets mit wichtiger Bedeutung in der Physik.",
    symbols: [
      { char: "Γ", name: "Gamma (gross)", latex: "\\Gamma", htmlEntity: "&Gamma;", unicode: "U+0393", beschreibung: "Gammafunktion, Zerfallsrate oder Christoffel-Symbole in der allgemeinen Relativitaetstheorie.", related: ["γ"] },
      { char: "Δ", name: "Delta (gross)", latex: "\\Delta", htmlEntity: "&Delta;", unicode: "U+0394", beschreibung: "Differenz oder Aenderung einer Groesse, z.B. Delta-T fuer Temperaturdifferenz.", related: ["δ"], beispiel: "∆E = mc² (Energieaenderung)" },
      { char: "Θ", name: "Theta (gross)", latex: "\\Theta", htmlEntity: "&Theta;", unicode: "U+0398", beschreibung: "Heaviside-Stufenfunktion oder Debye-Temperatur in der Festkoerperphysik.", related: ["θ"] },
      { char: "Λ", name: "Lambda (gross)", latex: "\\Lambda", htmlEntity: "&Lambda;", unicode: "U+039B", beschreibung: "Kosmologische Konstante, Lambda-Baryon oder Diagonalmatrix.", related: ["λ"] },
      { char: "Ξ", name: "Xi (gross)", latex: "\\Xi", htmlEntity: "&Xi;", unicode: "U+039E", beschreibung: "Xi-Baryon in der Teilchenphysik oder Kaskadenbaryon.", related: ["ξ"] },
      { char: "Π", name: "Pi (gross)", latex: "\\Pi", htmlEntity: "&Pi;", unicode: "U+03A0", beschreibung: "Produktsymbol (Multiplikation ueber Folgen) oder Peltier-Koeffizient.", related: ["π"] },
      { char: "Σ", name: "Sigma (gross)", latex: "\\Sigma", htmlEntity: "&Sigma;", unicode: "U+03A3", beschreibung: "Summenzeichen, Sigma-Baryon oder Spannungstensor.", related: ["σ"] },
      { char: "Φ", name: "Phi (gross)", latex: "\\Phi", htmlEntity: "&Phi;", unicode: "U+03A6", beschreibung: "Magnetischer Fluss, elektrischer Fluss oder allgemeines Potential.", related: ["φ"], beispiel: "Φ = B·A (Magnetischer Fluss)" },
      { char: "Ψ", name: "Psi (gross)", latex: "\\Psi", htmlEntity: "&Psi;", unicode: "U+03A8", beschreibung: "Gesamtwellenfunktion eines Quantensystems.", related: ["ψ"] },
      { char: "Ω", name: "Omega (gross)", latex: "\\Omega", htmlEntity: "&Omega;", unicode: "U+03A9", beschreibung: "Elektrischer Widerstand in Ohm, Raumwinkel oder Dichteparameter des Universums.", related: ["ω"] },
    ],
  },
  {
    id: "mathematisch",
    title: "Mathematische Operatoren",
    description: "Mathematische Symbole und Operatoren, die in physikalischen Gleichungen verwendet werden.",
    symbols: [
      { char: "∇", name: "Nabla", latex: "\\nabla", htmlEntity: "&nabla;", unicode: "U+2207", beschreibung: "Nabla-Operator: Gradient, Divergenz und Rotation von Vektorfeldern.", beispiel: "∇φ (Gradient von φ)" },
      { char: "∂", name: "Partielle Ableitung", latex: "\\partial", htmlEntity: "&part;", unicode: "U+2202", beschreibung: "Partielle Ableitung, z.B. in der Wellengleichung oder Maxwell-Gleichungen.", beispiel: "∂ψ/∂t (Zeitableitung)" },
      { char: "∫", name: "Integral", latex: "\\int", htmlEntity: "&int;", unicode: "U+222B", beschreibung: "Bestimmtes und unbestimmtes Integral zur Berechnung von Flaecheninhalten und Summen.", beispiel: "∫F·ds (Arbeit)" },
      { char: "∮", name: "Ringintegral", latex: "\\oint", unicode: "U+222E", beschreibung: "Geschlossenes Kurvenintegral, z.B. in den Maxwell-Gleichungen.", beispiel: "∮E·ds = 0 (Maxwell)" },
      { char: "∑", name: "Summe", latex: "\\sum", htmlEntity: "&sum;", unicode: "U+2211", beschreibung: "Summenzeichen fuer die Addition von Reihen und Folgen.", beispiel: "∑F = ma (Newtons 2. Gesetz)" },
      { char: "∏", name: "Produkt", latex: "\\prod", htmlEntity: "&prod;", unicode: "U+220F", beschreibung: "Produktzeichen fuer die Multiplikation von Reihen." },
      { char: "√", name: "Wurzel", latex: "\\sqrt{}", htmlEntity: "&radic;", unicode: "U+221A", beschreibung: "Quadratwurzel, z.B. bei der Berechnung von Betraegen oder Energien." },
      { char: "∞", name: "Unendlich", latex: "\\infty", htmlEntity: "&infin;", unicode: "U+221E", beschreibung: "Unendlichkeit, z.B. als Integrationsgrenze oder in Grenzwerten." },
      { char: "≈", name: "Ungefaehr gleich", latex: "\\approx", htmlEntity: "&asymp;", unicode: "U+2248", beschreibung: "Naeherungsweise Gleichheit, oft in der Physik fuer Abschaetzungen." },
      { char: "≠", name: "Ungleich", latex: "\\neq", htmlEntity: "&ne;", unicode: "U+2260", beschreibung: "Ungleichheit zweier Ausdruecke oder Groessen." },
      { char: "≤", name: "Kleiner gleich", latex: "\\leq", htmlEntity: "&le;", unicode: "U+2264", beschreibung: "Kleiner oder gleich, z.B. bei Ungleichungen in der Thermodynamik." },
      { char: "≥", name: "Groesser gleich", latex: "\\geq", htmlEntity: "&ge;", unicode: "U+2265", beschreibung: "Groesser oder gleich, z.B. in der Heisenbergschen Unschaerferelation." },
      { char: "±", name: "Plus-Minus", latex: "\\pm", htmlEntity: "&plusmn;", unicode: "U+00B1", beschreibung: "Plus-Minus-Zeichen fuer Fehlerangaben oder Loesungen quadratischer Gleichungen." },
      { char: "∝", name: "Proportional", latex: "\\propto", htmlEntity: "&prop;", unicode: "U+221D", beschreibung: "Proportionalitaet, z.B. F ist proportional zu a (Newtons zweites Gesetz)." },
      { char: "⟨⟩", name: "Bra-Ket", latex: "\\langle\\rangle", unicode: "U+27E8 U+27E9", beschreibung: "Dirac-Notation in der Quantenmechanik fuer Erwartungswerte und Zustaende." },
    ],
  },
  {
    id: "konstanten",
    title: "Physikalische Konstanten & Symbole",
    description: "Haeufig verwendete Symbole fuer physikalische Konstanten und Groessen.",
    symbols: [
      { char: "ℏ", name: "h-quer", latex: "\\hbar", unicode: "U+210F", beschreibung: "Reduziertes Plancksches Wirkungsquantum (h/2*pi), fundamental in der Quantenmechanik." },
      { char: "ℓ", name: "Kleines L", latex: "\\ell", unicode: "U+2113", beschreibung: "Laenge, Drehimpulsquantenzahl oder mittlere freie Weglaenge." },
      { char: "℃", name: "Grad Celsius", htmlEntity: "&deg;C", unicode: "U+2103", beschreibung: "Temperatureinheit Grad Celsius, basierend auf der Celsius-Skala." },
      { char: "Å", name: "Angstroem", latex: "\\AA", htmlEntity: "&Aring;", unicode: "U+00C5", beschreibung: "Laengeneinheit (10^-10 m), haeufig in der Atom- und Molekuelphysik." },
      { char: "→", name: "Pfeil rechts", latex: "\\rightarrow", htmlEntity: "&rarr;", unicode: "U+2192", beschreibung: "Vektorpfeil, Reaktionspfeil oder Grenzwertuebergang." },
      { char: "⇌", name: "Gleichgewichtspfeil", unicode: "U+21CC", beschreibung: "Chemisches Gleichgewicht, reversible Reaktionen." },
      { char: "†", name: "Dagger", latex: "\\dagger", htmlEntity: "&dagger;", unicode: "U+2020", beschreibung: "Adjungierter Operator in der Quantenmechanik (hermitesch konjugiert)." },
      { char: "⊗", name: "Tensorprodukt", latex: "\\otimes", htmlEntity: "&otimes;", unicode: "U+2297", beschreibung: "Tensorprodukt oder Kreuzprodukt in der Quantenmechanik." },
      { char: "⊕", name: "Direkte Summe", latex: "\\oplus", htmlEntity: "&oplus;", unicode: "U+2295", beschreibung: "Direkte Summe von Vektorraeumen oder XOR-Operation." },
      { char: "·", name: "Malpunkt", latex: "\\cdot", htmlEntity: "&middot;", unicode: "U+00B7", beschreibung: "Skalarprodukt von Vektoren oder Multiplikation." },
      { char: "×", name: "Kreuzprodukt", latex: "\\times", htmlEntity: "&times;", unicode: "U+00D7", beschreibung: "Vektorprodukt (Kreuzprodukt) oder Multiplikation." },
    ],
  },
  {
    id: "indizes",
    title: "Hoch- & Tiefstellungen",
    description: "Hoch- und tiefgestellte Ziffern und Buchstaben fuer Formeln und Einheiten.",
    symbols: [
      { char: "⁰", name: "Hochgestellt 0", beschreibung: "Hochgestellte Null, z.B. fuer Exponenten oder Gradangaben." },
      { char: "¹", name: "Hochgestellt 1", beschreibung: "Hochgestellte Eins, z.B. in Einheiten wie m/s oder s^-1." },
      { char: "²", name: "Hochgestellt 2", beschreibung: "Quadrat, z.B. in m^2 (Quadratmeter) oder E=mc^2." },
      { char: "³", name: "Hochgestellt 3", beschreibung: "Kubik, z.B. in m^3 (Kubikmeter) oder Volumensberechnungen." },
      { char: "⁴", name: "Hochgestellt 4", beschreibung: "Vierte Potenz, z.B. im Stefan-Boltzmann-Gesetz (T^4)." },
      { char: "⁻", name: "Hochgestellt Minus", beschreibung: "Negativer Exponent, z.B. in s^-1 (pro Sekunde) oder m^-2." },
      { char: "ⁿ", name: "Hochgestellt n", beschreibung: "Allgemeine Potenz n, z.B. in allgemeinen Formeln." },
      { char: "₀", name: "Tiefgestellt 0", beschreibung: "Tiefgestellte Null, z.B. fuer Anfangswerte (v_0, x_0)." },
      { char: "₁", name: "Tiefgestellt 1", beschreibung: "Tiefgestellte Eins, z.B. fuer Indizes in Gleichungssystemen." },
      { char: "₂", name: "Tiefgestellt 2", beschreibung: "Tiefgestellte Zwei, z.B. fuer den zweiten Index." },
      { char: "ₙ", name: "Tiefgestellt n", beschreibung: "Tiefgestelltes n fuer allgemeine Indizes und Folgen." },
    ],
  },
  {
    id: "si-praefixe",
    title: "SI-Praefixe",
    description: "Vollstaendige Liste aller SI-Vorsatzzeichen fuer Groessenordnungen von 10^-24 bis 10^24.",
    symbols: [
      { char: "y", name: "Yocto", latex: "y", unicode: "U+0079", beschreibung: "SI-Praefix Yocto (10^-24), z.B. ym (Yoctometer).", beispiel: "1 ym = 10⁻²⁴ m" },
      { char: "z", name: "Zepto", latex: "z", unicode: "U+007A", beschreibung: "SI-Praefix Zepto (10^-21), z.B. zs (Zeptosekunde).", beispiel: "1 zs = 10⁻²¹ s" },
      { char: "a", name: "Atto", latex: "a", unicode: "U+0061", beschreibung: "SI-Praefix Atto (10^-18), z.B. as (Attosekunde).", beispiel: "1 as = 10⁻¹⁸ s" },
      { char: "f", name: "Femto", latex: "f", unicode: "U+0066", beschreibung: "SI-Praefix Femto (10^-15), z.B. fm (Femtometer).", beispiel: "1 fm = 10⁻¹⁵ m (Kerndurchmesser)" },
      { char: "p", name: "Pico", latex: "p", unicode: "U+0070", beschreibung: "SI-Praefix Pico (10^-12), z.B. pF (Picofarad).", beispiel: "1 pF = 10⁻¹² F" },
      { char: "n", name: "Nano", latex: "n", unicode: "U+006E", beschreibung: "SI-Praefix Nano (10^-9), z.B. nm (Nanometer).", beispiel: "1 nm = 10⁻⁹ m" },
      { char: "µ", name: "Mikro", latex: "\\mu", htmlEntity: "&micro;", unicode: "U+00B5", beschreibung: "SI-Praefix Mikro (10^-6), z.B. µm (Mikrometer).", beispiel: "1 µm = 10⁻⁶ m" },
      { char: "m", name: "Milli", latex: "m", unicode: "U+006D", beschreibung: "SI-Praefix Milli (10^-3), z.B. mm (Millimeter).", beispiel: "1 mm = 10⁻³ m" },
      { char: "c", name: "Centi", latex: "c", unicode: "U+0063", beschreibung: "SI-Praefix Centi (10^-2), z.B. cm (Centimeter).", beispiel: "1 cm = 10⁻² m" },
      { char: "d", name: "Deci", latex: "d", unicode: "U+0064", beschreibung: "SI-Praefix Deci (10^-1), z.B. dm (Decimeter).", beispiel: "1 dm = 10⁻¹ m" },
      { char: "da", name: "Deka", latex: "da", unicode: "U+0064 U+0061", beschreibung: "SI-Praefix Deka (10^1), z.B. dam (Dekameter).", beispiel: "1 dam = 10¹ m" },
      { char: "h", name: "Hecto", latex: "h", unicode: "U+0068", beschreibung: "SI-Praefix Hecto (10^2), z.B. hPa (Hectopascal).", beispiel: "1 hPa = 10² Pa" },
      { char: "k", name: "Kilo", latex: "k", unicode: "U+006B", beschreibung: "SI-Praefix Kilo (10^3), z.B. km (Kilometer).", beispiel: "1 km = 10³ m" },
      { char: "M", name: "Mega", latex: "M", unicode: "U+004D", beschreibung: "SI-Praefix Mega (10^6), z.B. MHz (Megahertz).", beispiel: "1 MHz = 10⁶ Hz" },
      { char: "G", name: "Giga", latex: "G", unicode: "U+0047", beschreibung: "SI-Praefix Giga (10^9), z.B. GHz (Gigahertz).", beispiel: "1 GHz = 10⁹ Hz" },
      { char: "T", name: "Tera", latex: "T", unicode: "U+0054", beschreibung: "SI-Praefix Tera (10^12), z.B. TB (Terabyte).", beispiel: "1 THz = 10¹² Hz" },
      { char: "P", name: "Peta", latex: "P", unicode: "U+0050", beschreibung: "SI-Praefix Peta (10^15), z.B. PB (Petabyte).", beispiel: "1 PHz = 10¹⁵ Hz" },
      { char: "E", name: "Exa", latex: "E", unicode: "U+0045", beschreibung: "SI-Praefix Exa (10^18), z.B. EB (Exabyte).", beispiel: "1 EHz = 10¹⁸ Hz" },
      { char: "Z", name: "Zetta", latex: "Z", unicode: "U+005A", beschreibung: "SI-Praefix Zetta (10^21), z.B. ZB (Zettabyte).", beispiel: "1 ZHz = 10²¹ Hz" },
      { char: "Y", name: "Yotta", latex: "Y", unicode: "U+0059", beschreibung: "SI-Praefix Yotta (10^24), z.B. YB (Yottabyte).", beispiel: "1 YHz = 10²⁴ Hz" },
    ],
  },
  {
    id: "einheiten",
    title: "Einheiten & Zahlenmengen",
    description: "Symbole fuer Einheiten, Winkelangaben und Zahlenmengen.",
    symbols: [
      { char: "°", name: "Grad", htmlEntity: "&deg;", unicode: "U+00B0", beschreibung: "Gradzeichen fuer Winkel oder Temperatur." },
      { char: "′", name: "Bogenminute", unicode: "U+2032", beschreibung: "Bogenminute (1/60 Grad) oder Ableitung in der Mathematik." },
      { char: "″", name: "Bogensekunde", unicode: "U+2033", beschreibung: "Bogensekunde (1/3600 Grad) oder zweite Ableitung." },
      { char: "ℕ", name: "Natuerliche Zahlen", htmlEntity: "&Nopf;", unicode: "U+2115", beschreibung: "Menge der natuerlichen Zahlen (1, 2, 3, ...)." },
      { char: "ℤ", name: "Ganze Zahlen", htmlEntity: "&Zopf;", unicode: "U+2124", beschreibung: "Menge der ganzen Zahlen (..., -2, -1, 0, 1, 2, ...)." },
      { char: "ℝ", name: "Reelle Zahlen", htmlEntity: "&Ropf;", unicode: "U+211D", beschreibung: "Menge der reellen Zahlen, fundamental in der Physik." },
      { char: "ℂ", name: "Komplexe Zahlen", htmlEntity: "&Copf;", unicode: "U+2102", beschreibung: "Menge der komplexen Zahlen, wichtig in der Quantenmechanik und Elektrodynamik." },
    ],
  },
  {
    id: "mengenlehre",
    title: "Mengenlehre & Logik",
    description: "Symbole fuer Mengenoperationen und logische Verknuepfungen.",
    symbols: [
      { char: "∈", name: "Element von", latex: "\\in", htmlEntity: "&isin;", unicode: "U+2208", beschreibung: "Ein Element ist in einer Menge enthalten." },
      { char: "∉", name: "Nicht Element von", latex: "\\notin", htmlEntity: "&notin;", unicode: "U+2209", beschreibung: "Ein Element ist nicht in einer Menge enthalten." },
      { char: "⊂", name: "Teilmenge", latex: "\\subset", htmlEntity: "&sub;", unicode: "U+2282", beschreibung: "A ist echte Teilmenge von B." },
      { char: "⊃", name: "Obermenge", latex: "\\supset", htmlEntity: "&sup;", unicode: "U+2283", beschreibung: "A ist echte Obermenge von B." },
      { char: "⊆", name: "Teilmenge oder gleich", latex: "\\subseteq", htmlEntity: "&sube;", unicode: "U+2286", beschreibung: "A ist Teilmenge von oder gleich B." },
      { char: "⊇", name: "Obermenge oder gleich", latex: "\\supseteq", htmlEntity: "&supe;", unicode: "U+2287", beschreibung: "A ist Obermenge von oder gleich B." },
      { char: "∪", name: "Vereinigung", latex: "\\cup", htmlEntity: "&cup;", unicode: "U+222A", beschreibung: "Vereinigungsmenge zweier Mengen." },
      { char: "∩", name: "Schnitt", latex: "\\cap", htmlEntity: "&cap;", unicode: "U+2229", beschreibung: "Schnittmenge zweier Mengen." },
      { char: "∅", name: "Leere Menge", latex: "\\emptyset", htmlEntity: "&empty;", unicode: "U+2205", beschreibung: "Die leere Menge ohne Elemente." },
      { char: "∀", name: "Fuer alle", latex: "\\forall", htmlEntity: "&forall;", unicode: "U+2200", beschreibung: "Allquantor: gilt fuer alle Elemente." },
      { char: "∃", name: "Es existiert", latex: "\\exists", htmlEntity: "&exist;", unicode: "U+2203", beschreibung: "Existenzquantor: es gibt mindestens ein Element." },
      { char: "∄", name: "Es existiert nicht", latex: "\\nexists", unicode: "U+2204", beschreibung: "Es gibt kein solches Element." },
      { char: "∧", name: "Und", latex: "\\land", htmlEntity: "&and;", unicode: "U+2227", beschreibung: "Logische Und-Verknuepfung (Konjunktion)." },
      { char: "∨", name: "Oder", latex: "\\lor", htmlEntity: "&or;", unicode: "U+2228", beschreibung: "Logische Oder-Verknuepfung (Disjunktion)." },
      { char: "¬", name: "Nicht", latex: "\\neg", htmlEntity: "&not;", unicode: "U+00AC", beschreibung: "Logische Negation." },
      { char: "⇒", name: "Impliziert", latex: "\\Rightarrow", htmlEntity: "&rArr;", unicode: "U+21D2", beschreibung: "Wenn A dann B (Implikation)." },
      { char: "⇔", name: "Genau dann wenn", latex: "\\Leftrightarrow", htmlEntity: "&hArr;", unicode: "U+21D4", beschreibung: "A genau dann wenn B (Aequivalenz)." },
      { char: "∴", name: "Deshalb", latex: "\\therefore", htmlEntity: "&there4;", unicode: "U+2234", beschreibung: "Deshalb, folglich (in Beweisen)." },
      { char: "∵", name: "Weil", latex: "\\because", unicode: "U+2235", beschreibung: "Weil, da (in Beweisen)." },
      { char: "⊕", name: "XOR", latex: "\\oplus", htmlEntity: "&oplus;", unicode: "U+2295", beschreibung: "Exklusives Oder oder direkte Summe." },
      { char: "⊖", name: "MINUS", latex: "\\ominus", htmlEntity: "&ominus;", unicode: "U+2296", beschreibung: "Direktes Minus oder symmetrische Differenz." },
      { char: "⊢", name: "ableitbar", latex: "\\vdash", unicode: "U+22A2", beschreibung: "Ist ableitbar aus (in der Logik)." },
      { char: "⊤", name: "Wahr", latex: "\\top", unicode: "U+22A4", beschreibung: "Logischer Wert wahr (Tautologie)." },
      { char: "⊥", name: "Falsch", latex: "\\bot", unicode: "U+22A5", beschreibung: "Logischer Wert falsch (Widerspruch)." },
    ],
  },
  {
    id: "chemie",
    title: "Chemie & Reaktionen",
    description: "Symbole fuer chemische Reaktionsgleichungen und Aggregatzustaende.",
    symbols: [
      { char: "→", name: "Reaktionspfeil", latex: "\\rightarrow", htmlEntity: "&rarr;", unicode: "U+2192", beschreibung: "Pfeil fuer chemische Reaktionen, zeigt die Richtung der Reaktion an.", beispiel: "A + B → C" },
      { char: "⇌", name: "Gleichgewichtspfeil", latex: "\\rightleftharpoons", unicode: "U+21CC", beschreibung: "Chemisches Gleichgewicht, reversible Reaktionen.", beispiel: "H₂O ⇌ H⁺ + OH⁻" },
      { char: "⇄", name: "Reversibler Pfeil", latex: "\\leftrightarrow", htmlEntity: "&harr;", unicode: "U+2194", beschreibung: "Reversible Reaktion oder Gleichgewicht.", beispiel: "A ⇄ B" },
      { char: "↑", name: "Gas entsteht", latex: "\\uparrow", htmlEntity: "&uarr;", unicode: "U+2191", beschreibung: "Gasfoermiges Produkt entsteht (Pfeil nach oben).", beispiel: "Zn + 2HCl → ZnCl₂ + H₂↑" },
      { char: "↓", name: "Niederschlag", latex: "\\downarrow", htmlEntity: "&darr;", unicode: "U+2193", beschreibung: "Feststoff faellt aus (Niederschlag, Pfeil nach unten).", beispiel: "Ag⁺ + Cl⁻ → AgCl↓" },
      { char: "∆", name: "Erhitzen", latex: "\\Delta", htmlEntity: "&Delta;", unicode: "U+0394", beschreibung: "Delta-Symbol fuer Erhitzen oder Waermezufuhr.", beispiel: "CaCO₃ --∆--> CaO + CO₂" },
      { char: "s", name: "Fest (solid)", latex: "s", unicode: "U+0073", beschreibung: "Aggregatzustand fest (solid), z.B. in Reaktionsgleichungen.", beispiel: "NaCl(s)" },
      { char: "l", name: "Fluessig (liquid)", latex: "l", unicode: "U+006C", beschreibung: "Aggregatzustand fluessig (liquid).", beispiel: "H₂O(l)" },
      { char: "g", name: "Gasfoermig (gas)", latex: "g", unicode: "U+0067", beschreibung: "Aggregatzustand gasfoermig (gas).", beispiel: "H₂O(g)" },
      { char: "aq", name: "Waessrige Loesung", latex: "aq", unicode: "U+0061 U+0071", beschreibung: "In Wasser geloest (aqueous).", beispiel: "NaCl(aq)" },
      { char: "°", name: "Standardzustand", latex: "^\\circ", htmlEntity: "&deg;", unicode: "U+00B0", beschreibung: "Standardzustand, z.B. bei Standardbildungsenthalpie.", beispiel: "∆H° (Standardenthalpie)" },
      { char: "‡", name: "Uebergangszustand", latex: "^\\ddagger", htmlEntity: "&Dagger;", unicode: "U+2021", beschreibung: "Uebergangszustand in der Reaktionskinetik (Doppelkreuz).", beispiel: "∆G‡ (Aktivierungsenergie)" },
    ],
  },
  {
    id: "quantenmechanik",
    title: "Quantenmechanik",
    description: "Symbole und Notationen der Quantenmechanik nach Dirac.",
    symbols: [
      { char: "|ψ⟩", name: "Ket", latex: "|\\psi\\rangle", unicode: "U+007C U+03C8 U+27E9", beschreibung: "Ket-Vektor: Quantenzustand in Dirac-Notation.", beispiel: "|ψ⟩ = α|0⟩ + β|1⟩" },
      { char: "⟨ψ|", name: "Bra", latex: "\\langle\\psi|", unicode: "U+27E8 U+03C8 U+007C", beschreibung: "Bra-Vektor: Dualvektor zum Ket.", beispiel: "⟨ψ|ψ⟩ = 1" },
      { char: "⟨φ|ψ⟩", name: "Bracket (Skalarprodukt)", latex: "\\langle\\phi|\\psi\\rangle", unicode: "U+27E8 U+03C6 U+007C U+03C8 U+27E9", beschreibung: "Bracket: Skalarprodukt zweier Quantenzustaende.", beispiel: "⟨φ|ψ⟩ = ∫φ*ψ dx" },
      { char: "ℏ", name: "h-quer", latex: "\\hbar", unicode: "U+210F", beschreibung: "Reduziertes Plancksches Wirkungsquantum (h/2π), fundamental in der Quantenmechanik.", beispiel: "E = ℏω" },
      { char: "⊗", name: "Tensorprodukt", latex: "\\otimes", htmlEntity: "&otimes;", unicode: "U+2297", beschreibung: "Tensorprodukt fuer zusammengesetzte Quantensysteme.", beispiel: "|ψ⟩⊗|φ⟩ = |ψφ⟩" },
      { char: "†", name: "Dagger (Adjungiert)", latex: "\\dagger", htmlEntity: "&dagger;", unicode: "U+2020", beschreibung: "Hermitesch konjugierter Operator (Adjungierte).", beispiel: "A† (adjungierter Operator)" },
      { char: "Tr", name: "Spur (Trace)", latex: "\\mathrm{Tr}", unicode: "U+0054 U+0072", beschreibung: "Spur eines Operators, Summe der Diagonalelemente.", beispiel: "Tr(ρ) = 1 (Dichtematrix)" },
      { char: "∂̂", name: "Operator", latex: "\\hat{O}", unicode: "U+004F U+0302", beschreibung: "Operator-Dach zur Kennzeichnung von Operatoren.", beispiel: "Ĥψ = Eψ (Schrödingergleichung)" },
    ],
  },
  {
    id: "elektrotechnik",
    title: "Elektrotechnik",
    description: "Symbole und Einheiten der Elektrotechnik und Elektronik.",
    symbols: [
      { char: "Ω", name: "Ohm", latex: "\\Omega", htmlEntity: "&Omega;", unicode: "U+03A9", beschreibung: "Einheit des elektrischen Widerstands.", beispiel: "R = 100 Ω" },
      { char: "V", name: "Volt", latex: "V", unicode: "U+0056", beschreibung: "Einheit der elektrischen Spannung.", beispiel: "U = 230 V" },
      { char: "A", name: "Ampere", latex: "A", unicode: "U+0041", beschreibung: "Einheit der elektrischen Stromstaerke.", beispiel: "I = 5 A" },
      { char: "F", name: "Farad", latex: "F", unicode: "U+0046", beschreibung: "Einheit der elektrischen Kapazitaet.", beispiel: "C = 100 µF" },
      { char: "H", name: "Henry", latex: "H", unicode: "U+0048", beschreibung: "Einheit der Induktivitaet.", beispiel: "L = 10 mH" },
      { char: "W", name: "Watt", latex: "W", unicode: "U+0057", beschreibung: "Einheit der elektrischen Leistung.", beispiel: "P = 60 W" },
      { char: "Hz", name: "Hertz", latex: "Hz", unicode: "U+0048 U+007A", beschreibung: "Einheit der Frequenz.", beispiel: "f = 50 Hz" },
      { char: "∠", name: "Phasenwinkel", latex: "\\angle", unicode: "U+2220", beschreibung: "Phasenwinkel in der Wechselstromtechnik.", beispiel: "U = 230V∠30°" },
      { char: "j", name: "Imaginaere Einheit (EE)", latex: "j", unicode: "U+006A", beschreibung: "Imaginaere Einheit in der Elektrotechnik (statt i).", beispiel: "Z = R + jX" },
      { char: "⊥", name: "Orthogonal/Senkrecht", latex: "\\perp", unicode: "U+22A5", beschreibung: "Orthogonal oder senkrecht zu.", beispiel: "E ⊥ B (Felder senkrecht)" },
    ],
  },
  {
    id: "formeln",
    title: "Physikalische Formeln",
    description: "Haeufig verwendete physikalische Formeln als komplette Ausdruecke.",
    symbols: [
      { char: "E = mc²", name: "Masse-Energie-Aequivalenz", latex: "E = mc^2", unicode: "U+0045 U+0020 U+003D U+0020 U+006D U+0063 U+00B2", beschreibung: "Einsteinische Masse-Energie-Aequivalenz: Energie entspricht Masse mal Lichtgeschwindigkeit zum Quadrat." },
      { char: "F = ma", name: "Newtons 2. Gesetz", latex: "F = ma", unicode: "U+0046 U+0020 U+003D U+0020 U+006D U+0061", beschreibung: "Kraft gleich Masse mal Beschleunigung - Grundgesetz der Mechanik." },
      { char: "E = ½mv²", name: "Kinetische Energie", latex: "E = \\frac{1}{2}mv^2", unicode: "U+0045 U+0020 U+003D U+0020 U+00BD U+006D U+0076 U+00B2", beschreibung: "Kinetische Energie: Haelfte der Masse mal Geschwindigkeit zum Quadrat." },
      { char: "E = mgh", name: "Potentielle Energie", latex: "E = mgh", unicode: "U+0045 U+0020 U+003D U+0020 U+006D U+0067 U+0068", beschreibung: "Potentielle Energie im Gravitationsfeld: Masse mal Erdbeschleunigung mal Hoehe." },
      { char: "λ = h/p", name: "De Broglie-Wellenlaenge", latex: "\\lambda = \\frac{h}{p}", unicode: "U+03BB U+0020 U+003D U+0020 U+0068 U+002F U+0070", beschreibung: "Wellenlaenge eines Teilchens: Planck-Konstante durch Impuls." },
      { char: "∆x∆p ≥ ℏ/2", name: "Heisenberg-Unschaerferelation", latex: "\\Delta x \\Delta p \\geq \\frac{\\hbar}{2}", unicode: "U+0394 U+0078 U+0394 U+0070 U+2265 U+210F U+002F U+0032", beschreibung: "Heisenbergsche Unschaerferelation: Orts- und Impulsunschärfe sind komplementär." },
      { char: "PV = nRT", name: "Ideales Gasgesetz", latex: "PV = nRT", unicode: "U+0050 U+0056 U+0020 U+003D U+0020 U+006E U+0052 U+0054", beschreibung: "Zustandsgleichung idealer Gase: Druck mal Volumen gleich Stoffmenge mal Gaskonstante mal Temperatur." },
      { char: "I = U/R", name: "Ohmsches Gesetz", latex: "I = \\frac{U}{R}", unicode: "U+0049 U+0020 U+003D U+0020 U+0055 U+002F U+0052", beschreibung: "Stromstaerke gleich Spannung durch Widerstand." },
      { char: "P = UI", name: "Elektrische Leistung", latex: "P = UI", unicode: "U+0050 U+0020 U+003D U+0020 U+0055 U+0049", beschreibung: "Elektrische Leistung gleich Spannung mal Stromstaerke." },
      { char: "c = λf", name: "Wellengeschwindigkeit", latex: "c = \\lambda f", unicode: "U+0063 U+0020 U+003D U+0020 U+03BB U+0066", beschreibung: "Ausbreitungsgeschwindigkeit einer Welle: Wellenlaenge mal Frequenz." },
      { char: "F = Gm₁m₂/r²", name: "Gravitationsgesetz", latex: "F = G\\frac{m_1 m_2}{r^2}", unicode: "U+0046 U+0020 U+003D U+0020 U+0047 U+006D U+2081 U+006D U+2082 U+002F U+0072 U+00B2", beschreibung: "Newtonsches Gravitationsgesetz: Anziehungskraft zwischen zwei Massen." },
      { char: "F = kq₁q₂/r²", name: "Coulomb-Gesetz", latex: "F = k\\frac{q_1 q_2}{r^2}", unicode: "U+0046 U+0020 U+003D U+0020 U+006B U+0071 U+2081 U+0071 U+2082 U+002F U+0072 U+00B2", beschreibung: "Coulomb-Kraft zwischen zwei Ladungen." },
    ],
  },
]
