export interface PhysicsSymbol {
  char: string
  name: string
  latex?: string
  htmlEntity?: string
  unicode?: string
  beschreibung: string
  related?: string[]
}

export interface SymbolCategory {
  id: string
  title: string
  description: string
  symbols: PhysicsSymbol[]
}

export const categories: SymbolCategory[] = [
  {
    id: "griechisch-klein",
    title: "Griechische Kleinbuchstaben",
    description: "Kleinbuchstaben des griechischen Alphabets, die in der Physik als Variablen und Konstanten verwendet werden.",
    symbols: [
      { char: "α", name: "Alpha", latex: "\\alpha", htmlEntity: "&alpha;", unicode: "U+03B1", beschreibung: "Wird oft als Winkel, Winkelbeschleunigung oder Feinstrukturkonstante verwendet.", related: ["Α"] },
      { char: "β", name: "Beta", latex: "\\beta", htmlEntity: "&beta;", unicode: "U+03B2", beschreibung: "Bezeichnet das Verhaeltnis v/c in der Relativitaetstheorie oder einen Winkel.", related: ["Β"] },
      { char: "γ", name: "Gamma", latex: "\\gamma", htmlEntity: "&gamma;", unicode: "U+03B3", beschreibung: "Lorentzfaktor in der speziellen Relativitaetstheorie, auch Gammastrahlung.", related: ["Γ"] },
      { char: "δ", name: "Delta (klein)", latex: "\\delta", htmlEntity: "&delta;", unicode: "U+03B4", beschreibung: "Kleine Aenderung einer Groesse, Dirac-Deltafunktion oder Kronecker-Delta.", related: ["Δ"] },
      { char: "ε", name: "Epsilon", latex: "\\varepsilon", htmlEntity: "&epsilon;", unicode: "U+03B5", beschreibung: "Elektrische Feldkonstante (Permittivitaet) oder kleine Groesse in der Stoerungstheorie." },
      { char: "ζ", name: "Zeta", latex: "\\zeta", htmlEntity: "&zeta;", unicode: "U+03B6", beschreibung: "Daempfungsverhaeltnis oder Riemann-Zeta-Funktion in der mathematischen Physik." },
      { char: "η", name: "Eta", latex: "\\eta", htmlEntity: "&eta;", unicode: "U+03B7", beschreibung: "Wirkungsgrad, dynamische Viskositaet oder Metrik in der Relativitaetstheorie." },
      { char: "θ", name: "Theta", latex: "\\theta", htmlEntity: "&theta;", unicode: "U+03B8", beschreibung: "Winkel in Polarkoordinaten, Streuwinkel oder Heaviside-Funktion.", related: ["Θ"] },
      { char: "ι", name: "Iota", latex: "\\iota", htmlEntity: "&iota;", unicode: "U+03B9", beschreibung: "Selten in der Physik, gelegentlich als Index oder Laufvariable." },
      { char: "κ", name: "Kappa", latex: "\\kappa", htmlEntity: "&kappa;", unicode: "U+03BA", beschreibung: "Kruemmung, thermische Leitfaehigkeit oder Dielektrizitaetskonstante." },
      { char: "λ", name: "Lambda (klein)", latex: "\\lambda", htmlEntity: "&lambda;", unicode: "U+03BB", beschreibung: "Wellenlaenge, Zerfallskonstante oder Eigenwert in der Quantenmechanik.", related: ["Λ"] },
      { char: "μ", name: "My", latex: "\\mu", htmlEntity: "&mu;", unicode: "U+03BC", beschreibung: "Magnetische Permeabilitaet, Reibungskoeffizient, Mikro-Praefix (10^-6) oder reduzierte Masse." },
      { char: "ν", name: "Ny", latex: "\\nu", htmlEntity: "&nu;", unicode: "U+03BD", beschreibung: "Frequenz einer Welle, kinematische Viskositaet oder Neutrino-Symbol." },
      { char: "ξ", name: "Xi", latex: "\\xi", htmlEntity: "&xi;", unicode: "U+03BE", beschreibung: "Dimensionslose Koordinate oder Kohaerenzlaenge in der Supraleitung.", related: ["Ξ"] },
      { char: "π", name: "Pi", latex: "\\pi", htmlEntity: "&pi;", unicode: "U+03C0", beschreibung: "Kreiszahl (3,14159...), fundamentale Konstante in Geometrie und Physik.", related: ["Π"] },
      { char: "ρ", name: "Rho", latex: "\\rho", htmlEntity: "&rho;", unicode: "U+03C1", beschreibung: "Dichte, elektrischer Widerstand (spezifisch) oder Ladungsdichte." },
      { char: "σ", name: "Sigma (klein)", latex: "\\sigma", htmlEntity: "&sigma;", unicode: "U+03C3", beschreibung: "Stefan-Boltzmann-Konstante, Wirkungsquerschnitt, Spannung oder Standardabweichung.", related: ["Σ"] },
      { char: "τ", name: "Tau", latex: "\\tau", htmlEntity: "&tau;", unicode: "U+03C4", beschreibung: "Drehmoment, Zeitkonstante, Lebensdauer oder Schubspannung." },
      { char: "υ", name: "Ypsilon", latex: "\\upsilon", htmlEntity: "&upsilon;", unicode: "U+03C5", beschreibung: "Selten in der Physik; Ypsilon-Meson in der Teilchenphysik." },
      { char: "φ", name: "Phi (klein)", latex: "\\varphi", htmlEntity: "&phi;", unicode: "U+03C6", beschreibung: "Elektrisches Potential, Phasenwinkel oder Azimutwinkel in Kugelkoordinaten.", related: ["Φ"] },
      { char: "χ", name: "Chi", latex: "\\chi", htmlEntity: "&chi;", unicode: "U+03C7", beschreibung: "Magnetische Suszeptibilitaet, Chi-Quadrat-Test oder Wellenfunktion." },
      { char: "ψ", name: "Psi (klein)", latex: "\\psi", htmlEntity: "&psi;", unicode: "U+03C8", beschreibung: "Wellenfunktion in der Quantenmechanik oder Stromfunktion.", related: ["Ψ"] },
      { char: "ω", name: "Omega (klein)", latex: "\\omega", htmlEntity: "&omega;", unicode: "U+03C9", beschreibung: "Kreisfrequenz (2*pi*f), Winkelgeschwindigkeit oder Raumwinkel.", related: ["Ω"] },
    ],
  },
  {
    id: "griechisch-gross",
    title: "Griechische Grossbuchstaben",
    description: "Grossbuchstaben des griechischen Alphabets mit wichtiger Bedeutung in der Physik.",
    symbols: [
      { char: "Γ", name: "Gamma (gross)", latex: "\\Gamma", htmlEntity: "&Gamma;", unicode: "U+0393", beschreibung: "Gammafunktion, Zerfallsrate oder Christoffel-Symbole in der allgemeinen Relativitaetstheorie.", related: ["γ"] },
      { char: "Δ", name: "Delta (gross)", latex: "\\Delta", htmlEntity: "&Delta;", unicode: "U+0394", beschreibung: "Differenz oder Aenderung einer Groesse, z.B. Delta-T fuer Temperaturdifferenz.", related: ["δ"] },
      { char: "Θ", name: "Theta (gross)", latex: "\\Theta", htmlEntity: "&Theta;", unicode: "U+0398", beschreibung: "Heaviside-Stufenfunktion oder Debye-Temperatur in der Festkoerperphysik.", related: ["θ"] },
      { char: "Λ", name: "Lambda (gross)", latex: "\\Lambda", htmlEntity: "&Lambda;", unicode: "U+039B", beschreibung: "Kosmologische Konstante, Lambda-Baryon oder Diagonalmatrix.", related: ["λ"] },
      { char: "Ξ", name: "Xi (gross)", latex: "\\Xi", htmlEntity: "&Xi;", unicode: "U+039E", beschreibung: "Xi-Baryon in der Teilchenphysik oder Kaskadenbaryon.", related: ["ξ"] },
      { char: "Π", name: "Pi (gross)", latex: "\\Pi", htmlEntity: "&Pi;", unicode: "U+03A0", beschreibung: "Produktsymbol (Multiplikation ueber Folgen) oder Peltier-Koeffizient.", related: ["π"] },
      { char: "Σ", name: "Sigma (gross)", latex: "\\Sigma", htmlEntity: "&Sigma;", unicode: "U+03A3", beschreibung: "Summenzeichen, Sigma-Baryon oder Spannungstensor.", related: ["σ"] },
      { char: "Φ", name: "Phi (gross)", latex: "\\Phi", htmlEntity: "&Phi;", unicode: "U+03A6", beschreibung: "Magnetischer Fluss, elektrischer Fluss oder allgemeines Potential.", related: ["φ"] },
      { char: "Ψ", name: "Psi (gross)", latex: "\\Psi", htmlEntity: "&Psi;", unicode: "U+03A8", beschreibung: "Gesamtwellenfunktion eines Quantensystems.", related: ["ψ"] },
      { char: "Ω", name: "Omega (gross)", latex: "\\Omega", htmlEntity: "&Omega;", unicode: "U+03A9", beschreibung: "Elektrischer Widerstand in Ohm, Raumwinkel oder Dichteparameter des Universums.", related: ["ω"] },
    ],
  },
  {
    id: "mathematisch",
    title: "Mathematische Operatoren",
    description: "Mathematische Symbole und Operatoren, die in physikalischen Gleichungen verwendet werden.",
    symbols: [
      { char: "∇", name: "Nabla", latex: "\\nabla", htmlEntity: "&nabla;", unicode: "U+2207", beschreibung: "Nabla-Operator: Gradient, Divergenz und Rotation von Vektorfeldern." },
      { char: "∂", name: "Partielle Ableitung", latex: "\\partial", htmlEntity: "&part;", unicode: "U+2202", beschreibung: "Partielle Ableitung, z.B. in der Wellengleichung oder Maxwell-Gleichungen." },
      { char: "∫", name: "Integral", latex: "\\int", htmlEntity: "&int;", unicode: "U+222B", beschreibung: "Bestimmtes und unbestimmtes Integral zur Berechnung von Flaecheninhalten und Summen." },
      { char: "∮", name: "Ringintegral", latex: "\\oint", unicode: "U+222E", beschreibung: "Geschlossenes Kurvenintegral, z.B. in den Maxwell-Gleichungen." },
      { char: "∑", name: "Summe", latex: "\\sum", htmlEntity: "&sum;", unicode: "U+2211", beschreibung: "Summenzeichen fuer die Addition von Reihen und Folgen." },
      { char: "∏", name: "Produkt", latex: "\\prod", htmlEntity: "&prod;", unicode: "U+220F", beschreibung: "Produktzeichen fuer die Multiplikation von Reihen." },
      { char: "√", name: "Wurzel", latex: "\\sqrt{}", htmlEntity: "&radic;", unicode: "U+221A", beschreibung: "Quadratwurzel, z.B. bei der Berechnung von Betraegen oder Energien." },
      { char: "∞", name: "Unendlich", latex: "\\infty", htmlEntity: "&infin;", unicode: "U+221E", beschreibung: "Unendlichkeit, z.B. als Integrationsgrenze oder in Grenzwerten." },
      { char: "≈", name: "Ungefaehr gleich", latex: "\\approx", htmlEntity: "&asymp;", unicode: "U+2248", beschreibung: "Naeherungsweise Gleichheit, oft in der Physik fuer Abschaetzungen." },
      { char: "≠", name: "Ungleich", latex: "\\neq", htmlEntity: "&ne;", unicode: "U+2260", beschreibung: "Ungleichheit zweier Ausdruecke oder Groessen." },
      { char: "≤", name: "Kleiner gleich", latex: "\\leq", htmlEntity: "&le;", unicode: "U+2264", beschreibung: "Kleiner oder gleich, z.B. bei Ungleichungen in der Thermodynamik." },
      { char: "≥", name: "Groesser gleich", latex: "\\geq", htmlEntity: "&ge;", unicode: "U+2265", beschreibung: "Groesser oder gleich, z.B. in der Heisenbergschen Unschaerferelation." },
      { char: "±", name: "Plus-Minus", latex: "\\pm", htmlEntity: "&plusmn;", unicode: "U+00B1", beschreibung: "Plus-Minus-Zeichen fuer Fehlerangaben oder Loesungen quadratischer Gleichungen." },
      { char: "∝", name: "Proportional", latex: "\\propto", htmlEntity: "&prop;", unicode: "U+221D", beschreibung: "Proportionalitaet, z.B. F ist proportional zu a (Newtons zweites Gesetz)." },
      { char: "⟨⟩", name: "Bra-Ket", latex: "\\langle\\rangle", unicode: "U+27E8 U+27E9", beschreibung: "Dirac-Notation in der Quantenmechanik fuer Erwartungswerte und Zustaende." },
    ],
  },
  {
    id: "konstanten",
    title: "Physikalische Konstanten & Symbole",
    description: "Haeufig verwendete Symbole fuer physikalische Konstanten und Groessen.",
    symbols: [
      { char: "ℏ", name: "h-quer", latex: "\\hbar", unicode: "U+210F", beschreibung: "Reduziertes Plancksches Wirkungsquantum (h/2*pi), fundamental in der Quantenmechanik." },
      { char: "ℓ", name: "Kleines L", latex: "\\ell", unicode: "U+2113", beschreibung: "Laenge, Drehimpulsquantenzahl oder mittlere freie Weglaenge." },
      { char: "℃", name: "Grad Celsius", htmlEntity: "&deg;C", unicode: "U+2103", beschreibung: "Temperatureinheit Grad Celsius, basierend auf der Celsius-Skala." },
      { char: "Å", name: "Angstroem", latex: "\\AA", htmlEntity: "&Aring;", unicode: "U+00C5", beschreibung: "Laengeneinheit (10^-10 m), haeufig in der Atom- und Molekuelphysik." },
      { char: "→", name: "Pfeil rechts", latex: "\\rightarrow", htmlEntity: "&rarr;", unicode: "U+2192", beschreibung: "Vektorpfeil, Reaktionspfeil oder Grenzwertuebergang." },
      { char: "⇌", name: "Gleichgewichtspfeil", unicode: "U+21CC", beschreibung: "Chemisches Gleichgewicht, reversible Reaktionen." },
      { char: "†", name: "Dagger", latex: "\\dagger", htmlEntity: "&dagger;", unicode: "U+2020", beschreibung: "Adjungierter Operator in der Quantenmechanik (hermitesch konjugiert)." },
      { char: "⊗", name: "Tensorprodukt", latex: "\\otimes", htmlEntity: "&otimes;", unicode: "U+2297", beschreibung: "Tensorprodukt oder Kreuzprodukt in der Quantenmechanik." },
      { char: "⊕", name: "Direkte Summe", latex: "\\oplus", htmlEntity: "&oplus;", unicode: "U+2295", beschreibung: "Direkte Summe von Vektorraeumen oder XOR-Operation." },
      { char: "·", name: "Malpunkt", latex: "\\cdot", htmlEntity: "&middot;", unicode: "U+00B7", beschreibung: "Skalarprodukt von Vektoren oder Multiplikation." },
      { char: "×", name: "Kreuzprodukt", latex: "\\times", htmlEntity: "&times;", unicode: "U+00D7", beschreibung: "Vektorprodukt (Kreuzprodukt) oder Multiplikation." },
    ],
  },
  {
    id: "indizes",
    title: "Hoch- & Tiefstellungen",
    description: "Hoch- und tiefgestellte Ziffern und Buchstaben fuer Formeln und Einheiten.",
    symbols: [
      { char: "⁰", name: "Hochgestellt 0", beschreibung: "Hochgestellte Null, z.B. fuer Exponenten oder Gradangaben." },
      { char: "¹", name: "Hochgestellt 1", beschreibung: "Hochgestellte Eins, z.B. in Einheiten wie m/s oder s^-1." },
      { char: "²", name: "Hochgestellt 2", beschreibung: "Quadrat, z.B. in m^2 (Quadratmeter) oder E=mc^2." },
      { char: "³", name: "Hochgestellt 3", beschreibung: "Kubik, z.B. in m^3 (Kubikmeter) oder Volumensberechnungen." },
      { char: "⁴", name: "Hochgestellt 4", beschreibung: "Vierte Potenz, z.B. im Stefan-Boltzmann-Gesetz (T^4)." },
      { char: "⁻", name: "Hochgestellt Minus", beschreibung: "Negativer Exponent, z.B. in s^-1 (pro Sekunde) oder m^-2." },
      { char: "ⁿ", name: "Hochgestellt n", beschreibung: "Allgemeine Potenz n, z.B. in allgemeinen Formeln." },
      { char: "₀", name: "Tiefgestellt 0", beschreibung: "Tiefgestellte Null, z.B. fuer Anfangswerte (v_0, x_0)." },
      { char: "₁", name: "Tiefgestellt 1", beschreibung: "Tiefgestellte Eins, z.B. fuer Indizes in Gleichungssystemen." },
      { char: "₂", name: "Tiefgestellt 2", beschreibung: "Tiefgestellte Zwei, z.B. fuer den zweiten Index." },
      { char: "ₙ", name: "Tiefgestellt n", beschreibung: "Tiefgestelltes n fuer allgemeine Indizes und Folgen." },
    ],
  },
  {
    id: "einheiten",
    title: "SI-Einheiten & Praefixe",
    description: "Symbole fuer SI-Einheiten und Vorsatzzeichen fuer Groessenordnungen.",
    symbols: [
      { char: "µ", name: "Mikro", htmlEntity: "&micro;", unicode: "U+00B5", beschreibung: "SI-Praefix Mikro (10^-6), z.B. Mikrometer oder Mikrofarad." },
      { char: "°", name: "Grad", htmlEntity: "&deg;", unicode: "U+00B0", beschreibung: "Gradzeichen fuer Winkel oder Temperatur." },
      { char: "′", name: "Bogenminute", unicode: "U+2032", beschreibung: "Bogenminute (1/60 Grad) oder Ableitung in der Mathematik." },
      { char: "″", name: "Bogensekunde", unicode: "U+2033", beschreibung: "Bogensekunde (1/3600 Grad) oder zweite Ableitung." },
      { char: "ℕ", name: "Natuerliche Zahlen", htmlEntity: "&Nopf;", unicode: "U+2115", beschreibung: "Menge der natuerlichen Zahlen (1, 2, 3, ...)." },
      { char: "ℤ", name: "Ganze Zahlen", htmlEntity: "&Zopf;", unicode: "U+2124", beschreibung: "Menge der ganzen Zahlen (..., -2, -1, 0, 1, 2, ...)." },
      { char: "ℝ", name: "Reelle Zahlen", htmlEntity: "&Ropf;", unicode: "U+211D", beschreibung: "Menge der reellen Zahlen, fundamental in der Physik." },
      { char: "ℂ", name: "Komplexe Zahlen", htmlEntity: "&Copf;", unicode: "U+2102", beschreibung: "Menge der komplexen Zahlen, wichtig in der Quantenmechanik und Elektrodynamik." },
    ],
  },
  {
    id: "mengenlehre",
    title: "Mengenlehre & Logik",
    description: "Symbole fuer Mengenoperationen und logische Verknuepfungen.",
    symbols: [
      { char: "∈", name: "Element von", latex: "\\in", htmlEntity: "&isin;", unicode: "U+2208", beschreibung: "Ein Element ist in einer Menge enthalten." },
      { char: "∉", name: "Nicht Element von", latex: "\\notin", htmlEntity: "&notin;", unicode: "U+2209", beschreibung: "Ein Element ist nicht in einer Menge enthalten." },
      { char: "⊂", name: "Teilmenge", latex: "\\subset", htmlEntity: "&sub;", unicode: "U+2282", beschreibung: "A ist echte Teilmenge von B." },
      { char: "⊃", name: "Obermenge", latex: "\\supset", htmlEntity: "&sup;", unicode: "U+2283", beschreibung: "A ist echte Obermenge von B." },
      { char: "⊆", name: "Teilmenge oder gleich", latex: "\\subseteq", htmlEntity: "&sube;", unicode: "U+2286", beschreibung: "A ist Teilmenge von oder gleich B." },
      { char: "⊇", name: "Obermenge oder gleich", latex: "\\supseteq", htmlEntity: "&supe;", unicode: "U+2287", beschreibung: "A ist Obermenge von oder gleich B." },
      { char: "∪", name: "Vereinigung", latex: "\\cup", htmlEntity: "&cup;", unicode: "U+222A", beschreibung: "Vereinigungsmenge zweier Mengen." },
      { char: "∩", name: "Schnitt", latex: "\\cap", htmlEntity: "&cap;", unicode: "U+2229", beschreibung: "Schnittmenge zweier Mengen." },
      { char: "∅", name: "Leere Menge", latex: "\\emptyset", htmlEntity: "&empty;", unicode: "U+2205", beschreibung: "Die leere Menge ohne Elemente." },
      { char: "∀", name: "Fuer alle", latex: "\\forall", htmlEntity: "&forall;", unicode: "U+2200", beschreibung: "Allquantor: gilt fuer alle Elemente." },
      { char: "∃", name: "Es existiert", latex: "\\exists", htmlEntity: "&exist;", unicode: "U+2203", beschreibung: "Existenzquantor: es gibt mindestens ein Element." },
      { char: "∄", name: "Es existiert nicht", latex: "\\nexists", unicode: "U+2204", beschreibung: "Es gibt kein solches Element." },
      { char: "∧", name: "Und", latex: "\\land", htmlEntity: "&and;", unicode: "U+2227", beschreibung: "Logische Und-Verknuepfung (Konjunktion)." },
      { char: "∨", name: "Oder", latex: "\\lor", htmlEntity: "&or;", unicode: "U+2228", beschreibung: "Logische Oder-Verknuepfung (Disjunktion)." },
      { char: "¬", name: "Nicht", latex: "\\neg", htmlEntity: "&not;", unicode: "U+00AC", beschreibung: "Logische Negation." },
      { char: "⇒", name: "Impliziert", latex: "\\Rightarrow", htmlEntity: "&rArr;", unicode: "U+21D2", beschreibung: "Wenn A dann B (Implikation)." },
      { char: "⇔", name: "Genau dann wenn", latex: "\\Leftrightarrow", htmlEntity: "&hArr;", unicode: "U+21D4", beschreibung: "A genau dann wenn B (Aequivalenz)." },
      { char: "∴", name: "Deshalb", latex: "\\therefore", htmlEntity: "&there4;", unicode: "U+2234", beschreibung: "Deshalb, folglich (in Beweisen)." },
      { char: "∵", name: "Weil", latex: "\\because", unicode: "U+2235", beschreibung: "Weil, da (in Beweisen)." },
      { char: "⊕", name: "XOR", latex: "\\oplus", htmlEntity: "&oplus;", unicode: "U+2295", beschreibung: "Exklusives Oder oder direkte Summe." },
      { char: "⊖", name: "MINUS", latex: "\\ominus", htmlEntity: "&ominus;", unicode: "U+2296", beschreibung: "Direktes Minus oder symmetrische Differenz." },
      { char: "⊢", name: "ableitbar", latex: "\\vdash", unicode: "U+22A2", beschreibung: "Ist ableitbar aus (in der Logik)." },
      { char: "⊤", name: "Wahr", latex: "\\top", unicode: "U+22A4", beschreibung: "Logischer Wert wahr (Tautologie)." },
      { char: "⊥", name: "Falsch", latex: "\\bot", unicode: "U+22A5", beschreibung: "Logischer Wert falsch (Widerspruch)." },
    ],
  },
]
